version: '3.2'
services:
  client:
    container_name: cts-client
    image: pratikadhau/cts-client:latest
    links:
        - server
    ports:
      - "3000:3000"

  server:
    container_name: cts-server
    image: pratikadhau/cts-server:latest
    ports:
      - "8080:8080"
